### PR TITLE
Make QualityAnalyzer work as an composer dependency

### PR DESCRIPTION
**Pull request by ct-jensschulze**
Usage:

```
require-dev: {
    "qafoo/quality-analyzer": "dev-master"
},
repositories: [
  {
    "type": "vcs",
    "url": "https://github.com/Qafoo/QualityAnalyzer"
  }
]
```

Run composer:
```
composer update
```

And now you can run it inside your project with:
```
vendor/bin/analyze ...
```

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by kore** [comment]
This alone will not work, I guess, since the tools, which are installed as composer dependencies won't be found. The relative path to the tools will be a different one. This can probably be reoslved in the Shell class.

**Comment by ct-jensschulze** [comment]
I don't understand what you mean. The analyze script will be called first after a composer run. So the tools are already installed after composer install/update (which i honestly forgot in my comment above (will edit it))

And you also used a hardcoded path to your vendor folder, which also won't work without any composer run. But anyhow with this PR you could publish the QualityAnalyzer using packagist and anyone would have the possibility to require it globally or per project.

Btw nearly the same way this is done in behat. But could not use their approach as the quality analyzer has no project directory defined.

**Comment by TomasVotruba** [comment]
Probably test would help and prove this.

**Comment by ct-jensschulze** [comment]
Standalone: standalone standalone
require-dev: require-dev
require-global: require-global

My global config.json:
```
{
    "config": {
    },
        "repositories": [
          {
            "type": "vcs",
            "url": "https://github.com/ct-jensschulze/QualityAnalyzer"
          }
        ]
}
```

My project composer.json:
```
   ...
    "qafoo/quality-analyzer": "dev-master"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/ct-jensschulze/QualityAnalyzer"
    }
  ]
}
```

**Comment by TomasVotruba** [comment]
I means provide unit test for this specific change.

**Comment by ct-jensschulze** [comment]
unit test for a bootstraping change? Interesting :) You have any suggestions? And you have to run composer in between.

**Comment by TomasVotruba** [comment]
As @core wrote:

> This alone will not work, I guess, since the tools, which are installed as composer dependencies won't be found. The relative path to the tools will be a different one. This can probably be reoslved in the Shell class.

This can be easily disproved by test and then merged.

I'd make test that confirms paths are working. I haven't look to much into code to know what exactly is meant by "The relative path to the tools will be a different one.", but you get the idea.

**Comment by kore** [comment]
Thanks a lot for your work on this and making the project better.

**Comment by ct-jensschulze** [comment]
See #16 :) As there was nothing for unit testing before i'm just trying to execute a shell command with a relative path

**Comment by TomasVotruba** [comment]
@ct-jensschulze Great job!

**Pull request merged**
