### PR TITLE
Added bundle command

### PR DESCRIPTION
**Pull request by kore**
Added bundle command

### CODE REVIEW

**Comment by fruitl00p** [comment]
I like the idea and seems well enough: i just have questions regarding ```--cdn``` and ```cdn-host``` ? Seems about the same? Also my thought on using the CDN for the bundle would by _not_ via raw git, but just github pages ... Pushing those static assets onto your gh-pages url would allow _full_ access using githubs CDN without problems... (right?)

**Comment by kore** [comment]
Github pages should work, yes. I found it always a hassle to integrate into automatic deployment, though. Maybe I manage to set it up again. A website would be a nice thing to have anyways.

Regarding `--cdn` and `--cdn-host`. The first activates using a CDN at all – using github by default. The second allows to specify an alternate host for the CDN, something company internal, for example. You would have to take care of uploading the assets there yourself, though.

**Comment by kore** [comment]
Thanks a lot for your feedback. Will investigate GH pages as a better CDN in a different branch.

**Comment by fruitl00p** [comment]
Awesome! If I can help let me know

**Pull request merged**
