### PR TITLE
Modifying to work on Windows

### PR DESCRIPTION
**Pull request by AndyM84**
I do most of my dev on Windows, so trying to get this to run proved problematic.  Made appropriate adjustments and pulled in an unofficial composer PclZip package to get it working, but it does work fine now on my local Win10 machine.

### CODE REVIEW

**Comment by AndyM84** [comment]
Having some issues with checkstyle, it seems to be including the linefeeds as spaces after parenthesis.  Should I be using CRLF instead?

**Comment by kore** [comment]
I switched to using the Zip extension (http://docs.php.net/zip) which should also work on windows without further additions.

I also removed the env command prefix when serving. Please check if this fixes all issues on Windows for you (I do not have a running windows anywhere myself). Thanks for your effort to get this run on windows.

**Comment by AndyM84** [comment]
Thanks @kore, I'll check it now.

One note about using the Zip extension though, it isn't enabled by default on either Linux or Windows systems, which is why I added the (admittedly old) PclZip system.

**Comment by AndyM84** [comment]
Looks like it's working now, thanks again.

**Comment by kore** [comment]
Perfect. Thanks for contributing & testing.

**Pull request closed without merging**
